# Generated by Django 3.2.8 on 2021-10-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_pelicula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='descripcion',
            new_name='description',
        ),
    ]
