# Generated by Django 3.2.8 on 2021-10-11 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado')),
                ('fm', models.DateTimeField(auto_now=True, verbose_name='fecha modificado')),
                ('um', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Nombre del proveedor')),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección')),
                ('contacto', models.CharField(max_length=100, verbose_name='Contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Correo electrónico')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
